# EDA

In [1]:
import pandas as pd
import numpy as np

data= {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'Marks': [85, 90, 95, 80, 75],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# creating sample dataset (10rows, 5 columns)

data= {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    'Marks': [85, 90, 95, 80, 75, 70, 65, 60, 55, 50],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 
             'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose']
}

df = pd.DataFrame(data)
df

      Name  Age  Marks          City
0    Alice   25     85      New York
1      Bob   30     90   Los Angeles
2  Charlie   35     95       Chicago
3    David   40     80       Houston
4      Eve   45     75       Phoenix
5    Frank   50     70  Philadelphia
6    Grace   55     65   San Antonio
7    Heidi   60     60     San Diego
8     Ivan   65     55        Dallas
9     Judy   70     50      San Jose

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   Marks   10 non-null     int64
 3   City    10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [3]:
df.isnull()

    Name    Age  Marks   City
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9  False  False  False  False

In [4]:
df.describe()

             Age      Marks
count  10.000000  10.000000
mean   47.500000  72.500000
std    15.138252  15.138252
min    25.000000  50.000000
25%    36.250000  61.250000
50%    47.500000  72.500000
75%    58.750000  83.750000
max    70.000000  95.000000

In [8]:
df_mean = df.copy()

In [9]:
df_mean['Age'].fillna(df['Age'].mean())

0    25
1    30
2    35
3    40
4    45
5    50
6    55
7    60
8    65
9    70
Name: Age, dtype: int64

In [10]:
df_mean

      Name  Age  Marks          City
0    Alice   25     85      New York
1      Bob   30     90   Los Angeles
2  Charlie   35     95       Chicago
3    David   40     80       Houston
4      Eve   45     75       Phoenix
5    Frank   50     70  Philadelphia
6    Grace   55     65   San Antonio
7    Heidi   60     60     San Diego
8     Ivan   65     55        Dallas
9     Judy   70     50      San Jose

In [11]:
data = {
    'Name': ['Amit', 'Riya', 'John', None, 'Sara', 'Raj', None],
    'Age': [23, np.nan, 25, 30, None, 28, 22],
    'Marks': [85, 90, None, 70, 88, None, 95],
    'City': ['Pune', 'Mumbai', None, 'Delhi', 'Pune', None, 'Mumbai']
}

In [12]:
df= pd.DataFrame(data)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Marks   5 non-null      float64
 3   City    5 non-null      object
dtypes: float64(2), object(2)
memory usage: 356.0+ bytes

In [14]:
df.describe

<bound method NDFrame.describe of    Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya   NaN   90.0  Mumbai
2  John  25.0    NaN    None
3  None  30.0   70.0   Delhi
4  Sara   NaN   88.0    Pune
5   Raj  28.0    NaN    None
6  None  22.0   95.0  Mumbai>

In [15]:
df_mean = df.copy()

In [16]:
df_mean['Age'].fillna(df['Age'].mean(), inplace=True)

/tmp/ipykernel_6231/3212440260.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Age'].fillna(df['Age'].mean(), inplace=True)

In [17]:
df_mean

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0    NaN    None
3  None  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0    NaN    None
6  None  22.0   95.0  Mumbai

In [ ]:
df_mean['Marks'].fillna(df['Marks'].median())

0    85.0
1    90.0
2    88.0
3    70.0
4    88.0
5    88.0
6    95.0
Name: Marks, dtype: float64

In [19]:
df_mean['Marks'].fillna(df['Marks'].median(), inplace=True)
df_mean

/tmp/ipykernel_6231/303370214.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Marks'].fillna(df['Marks'].median(), inplace=True)

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0   88.0    None
3  None  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0   88.0    None
6  None  22.0   95.0  Mumbai

In [20]:
df_mean['City'].fillna(df['City'].mode()[0], inplace=True)
df_mean

/tmp/ipykernel_6231/3940588406.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['City'].fillna(df['City'].mode()[0], inplace=True)

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0   88.0  Mumbai
3  None  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0   88.0  Mumbai
6  None  22.0   95.0  Mumbai

In [21]:
df_mean['Name'].drop_duplicates

<bound method Series.drop_duplicates of 0    Amit
1    Riya
2    John
3    None
4    Sara
5     Raj
6    None
Name: Name, dtype: object>

In [22]:
df_copy = df.copy()

In [23]:
df_copy['Age'].fillna(df_copy['Age'].mean(), inplace=True)
df_copy['Marks'].fillna(df_copy['Marks'].median(), inplace=True)

/tmp/ipykernel_6231/2004294058.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['Age'].fillna(df_copy['Age'].mean(), inplace=True)
/tmp/ipykernel_6231/2004294058.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_copy['Marks'].fillna(df_copy['Marks'].median(), inplace=True)

In [24]:
df_copy

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0   88.0    None
3  None  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0   88.0    None
6  None  22.0   95.0  Mumbai

In [26]:
df_copy.fillna(method='ffill')

/tmp/ipykernel_6231/395579363.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_copy.fillna(method='ffill')

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0   88.0  Mumbai
3  John  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0   88.0    Pune
6   Raj  22.0   95.0  Mumbai

In [27]:
df_copy.fillna(method='bfill')

/tmp/ipykernel_6231/546085755.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_copy.fillna(method='bfill')

   Name   Age  Marks    City
0  Amit  23.0   85.0    Pune
1  Riya  25.6   90.0  Mumbai
2  John  25.0   88.0  Mumbai
3  John  30.0   70.0   Delhi
4  Sara  25.6   88.0    Pune
5   Raj  28.0   88.0    Pune
6   Raj  22.0   95.0  Mumbai

In [28]:
df_copy['Name'].drop_duplicates()

0    Amit
1    Riya
2    John
4    Sara
5     Raj
Name: Name, dtype: object